### PR TITLE
Windows x64 m49 binaries

### PR DESCRIPTION
**Pull request by zorn-v**
Works with Atom 1.14.0 x64

### CODE REVIEW

**Comment by ivankravets** [comment]
Thanks a lot! 👍

**Comment by ivankravets** [comment]
@zorn-v could you provide binaries for M53? New Atom 1.19.

Thanks!

**Comment by zorn-v** [comment]
Seems binaries are OK. You can try uninstall/install platformio-ide-terminal without rebuilding and it will work. Problem in another place I think. I get https://github.com/platformio/platformio-atom-ide-terminal/issues/304 issue when update module and atom by hand. After "rebuilding", binaries does not changed.

**Comment by ivankravets** [comment]
Yes, we built them yesterday. Sorry for disturb.

**Comment by ivankravets** [comment]
@zorn-v could you help us with binaries for Atom 1.25 m54?

**Pull request merged**
